[package]
name = "crate_axum_middleware_auth"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5"
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }