# The runtime environment has ADMIN_KEY and the request query parameter is admin_key
# The values must match
# The NaiveDateTime type in Rust expects a specific format, which includes seconds. 
# The correct format should be YYYY-MM-DDTHH:MM:SS.
POST http://localhost:3001/insert HTTP/1.1
content-type: application/json

{
        "name": "Bob",
        "success": true
}
